<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Histórico de Partidas</title>
</head>

<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        padding-left: 50px;
        padding-right: 50px;
        padding-top: 20px;
        padding-bottom: 20px;

    }
</style>

<body>
<h1 style="text-align: center; margin-top: 100px">Histórico de Partidas</h1>

<div style="max-width: 960px; margin: auto; margin-top: 100px">
    <table style="margin: auto">
        <tr>
            <th>#</th>
            <th>Pontuação</th>
            <th>Resultado</th>
            <th>Data</th>
        </tr>
        <tr>
            <th>3</th>
            <th>12</th>
            <th>Perdeu</th>
            <th>06/05/2020</th>
        </tr>
        <tr>
            <th>2</th>
            <th>6</th>
            <th>Ganhou</th>
            <th>04/05/2020</th>
        </tr>
        <tr>
            <th>1</th>
            <th>10</th>
            <th>Ganhou</th>
            <th>03/05/2020</th>
        </tr>
    </table>
</div>

</body>
</html>