<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('headerproject');
?>
<div class="container mt-5">
    <div style="border: 2px solid #e0e0ca;"  class="gameBox">
        <div class="row">
            <div class="col-sm text-center">
                <button type="button" class="btn btn-info">1</button>
            </div>
            <div class="col-sm text-center">
                <button type="button" class="btn btn-info">2</button>
            </div>
            <div class="col-sm text-center">
                <button type="button" class="btn btn-info">3</button>
            </div>
            <div class="col-sm text-center">
                <button type="button" class="btn btn-info">4</button>
            </div>
            <div class="col-sm text-center">
                <button type="button" class="btn btn-info">5</button>
            </div>
            <div class="col-sm text-center">
                <button type="button" class="btn btn-info">6</button>
            </div>
            <div class="col-sm text-center">
                <button type="button" class="btn btn-info">7</button>
            </div>
            <div class="col-sm text-center">
                <button type="button" class="btn btn-info">8</button>
            </div>
            <div class="col-sm text-center">
                <button type="button" class="btn btn-info">9</button>
            </div>

        </div>
    </div>
</div>