<?php

use ArmoredCore\WebObjects\Layout;

Layout::includeLayout('headerproject');
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contas</title>
</head>



<body>
<h1 style="text-align: center; margin-top: 100px">Backoffice</h1>


<div style="margin-top: 3%" class="container">

    <table class="table table-hover">
        <thead>
        <tr>
            <th>Username</th>
            <th>Bloqueada</th>
            <th>Data</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th>TiagoLopes</th>
            <th>X</th>
            <th>06/05/2020</th>
            <th><button>Desbloquear</button></th>
        </tr>
        <tr>
            <th>DavidSilverio</th>
            <th></th>
            <th></th>
            <th><button>Bloquear</button></th>
        </tr>
        <tr>
            <th>AfonsoCancela</th>
            <th>X</th>
            <th>04/05/2020</th>
            <th><button>Desbloquear</button></th>
        </tr>
        </tbody>
    </table>
</div>

</body>
</html>