<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contas</title>
</head>

<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        padding: 5px;
    }
</style>

<body>
<h1 style="text-align: center">Backoffice</h1>
<div style="max-width: 960px; margin: auto; margin-top: 150px">

    <div style="text-align: center">
        Pesquisar: <input type="text">
    </div>

    <table style="margin: auto;margin-top: 50px;">
        <tr>
            <th>Username</th>
            <th>Bloqueada</th>
            <th>Descricao</th>
            <th>Data</th>
        </tr>
        <tr>
            <th>TiagoLopes</th>
            <th>X</th>
            <th>Batota</th>
            <th>06/05/2020</th>
            <th><button>Desbloquear</button></th>
        </tr>
        <tr>
            <th>DavidSilverio</th>
            <th></th>
            <th></th>
            <th></th>
            <th><button>Bloquear</button></th>
        </tr>
        <tr>
            <th>AfonsoCancela</th>
            <th>X</th>
            <th>Batota</th>
            <th>04/05/2020</th>
            <th><button>Desbloquear</button></th>
        </tr>
    </table>
</div>

</body>
</html>