<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('headerproject');
?>


<div style="padding-top: 56px" class="container">

<!-- Heading Row -->
<div class="row align-items-center my-5">
    <div class="col-lg-7">
        <img class="img-fluid rounded mb-4 mb-lg-0" src="http://placehold.it/900x400" alt="">
    </div>
    <!-- /.col-lg-8 -->
    <div class="col-lg-5">
        <h1 class="font-weight-light">Welcome to Shut the Box Game</h1>
        <p>Shut the Box is a game of dice that became popular for many reasons, the first because it is a simple game, the second because it is extremely fun to play.</p>
        <a class="btn btn-primary" href="#">Let's play!</a>
    </div>
    <!-- /.col-md-4 -->
</div>
    <br>
<!-- /.row -->


<!-- Content Row -->
<div class="row">
    <div class="col-md-4 mb-5">
        <div class="card h-100">
            <div class="card-body">
                <h2 class="card-title">Game Rules</h2>
                <p class="card-text">Before start playing we recommend you to check out the game rules.</p>
            </div>
            <div class="card-footer">
                <a href="<?= URL::toRoute('rules/')?>" class="btn btn-primary btn-sm">Game Rules</a>
            </div>
        </div>
    </div>
    <!-- /.col-md-4 -->
    <div class="col-md-4 mb-5">
        <div class="card h-100">
            <div class="card-body">
                <h2 class="card-title">Leaderboard</h2>
                <p class="card-text">Our system also benefits from a leaderboard created for the hardcore users that take competitivity to the next level.</p>
            </div>
            <div class="card-footer">
                <a href="<?= URL::toRoute('top10/')?>" class="btn btn-primary btn-sm">Leaderboard</a>
            </div>
        </div>
    </div>
    <!-- /.col-md-4 -->
    <div class="col-md-4 mb-5">
        <div class="card h-100">
            <div class="card-body">
                <h2 class="card-title">Sign Up or Login</h2>
                <p class="card-text">In order to play you have to be signed up in our system. If you are already signed up you just got to login and play!</p>
            </div>
            <div class="card-footer">
                <a href="<?= URL::toRoute('login/')?>" class="btn btn-primary btn-sm">More Info</a>
            </div>
        </div>
    </div>
    <!-- /.col-md-4 -->

</div>
<!-- /.row -->

</div>
<!-- /.container -->

</body>

<?php Layout::includeLayout('footerproject'); ?>
