<footer style="margin-top: 10%" id="footer-static" class="py-4 bg-dark text-white-50 static-bottom">

    <div class="container">
        <div class="row">
            <div class="col-sm">
                Desenvolvedores:<br><br>
                Afonso Cancela<br>
                David Silvério<br>
                Tiago Lopes
            </div>
            <div class="col-sm" style="font-size: 20px">
                <br>
                Instituto Politécnico de Leiria
            </div>
            <div class="col-sm">
                Professora:<br><br>
                Joana Pedrosa
            </div>
        </div>
    </div>
</footer>


</body>
</html>