<?php
use ArmoredCore\WebObjects\Layout;
Layout::includeLayout('headerproject');
?>

    <body>
    <div style="margin-top: 3%" class="container">
        <h3>Leaderboard</h3>
        <select class="pull-right">
            <option value="">First to last</option>
            <option value="">Last to first</option>
        </select>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Username</th>
                <th>Points</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th>1</th>
                <td>Tiago Lopes</td>
                <td>tiagolopes</td>
                <td>0</td>
            </tr>
            <tr>
                <th>2</th>
                <td>David Silvério</td>
                <td>davidsilverio</td>
                <td>3</td>
            </tr>
            <tr>
                <th>3</th>
                <td>Afonso Cancela</td>
                <td>cancelafonso</td>
                <td>7</td>
            </tr>
            <tr>
                <th>4</th>
                <td>Major Santos</td>
                <td>jorsantos</td>
                <td>8</td>
            </tr>
            <tr>
                <th>5</th>
                <td>Rodrigo Silva</td>
                <td>rodsilvas</td>
                <td>11</td>
            </tr>
            <tr>
                <th>6</th>
                <td>André Gaspar</td>
                <td>strongvow</td>
                <td>13</td>
            </tr>
            <tr>
                <th>7</th>
                <td>Paulo Cardozo</td>
                <td>cardozo</td>
                <td>13</td>
            </tr>
            <tr>
                <th>8</th>
                <td>Rodrigo Valverde</td>
                <td>valverdepower</td>
                <td>18</td>
            </tr>
            <tr>
                <th>9</th>
                <td>Pedro Rainho</td>
                <td>rainhoIntheHouse</td>
                <td>21</td>
            </tr>
            <tr>
                <th>10</th>
                <td>Jorge Andrade</td>
                <td>cabaleroandrade</td>
                <td>22</td>
            </tr>
            </tbody>
        </table>
    </div>


    </body>

<?php Layout::includeLayout('footerproject');?>