<?php
use ArmoredCore\WebObjects\URL;
?>

<head>
    <meta charset="utf-8">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <title>Shut the Box Game</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>


<body style="margin-top: 10%" class="text-center">
<div style="max-width: 550px; border: 1px solid grey; padding-top: 2%; background-color: whitesmoke" class="container">
    <form class="form-signin">
<!--        <img class="mb-4" src="" alt="" width=92" height="92">-->
        <h1 style="padding-bottom: 2%;" class="h2 mb-3 font-weight-normal">Sign Up</h1>
        <div class="form-label-group">
            <input type="text" id="inputEmail" class="form-control" placeholder="Name" required autofocus>
            <label for="inputName" class=""></label>
        </div >
        <div class="form-label-group">
            <input type="email" id="inputName" class="form-control" placeholder="Email" required>
            <label for="inputEmail" class=""></label>
        </div>
        <div class="form-label-group">
            <input type="text" id="inputUsername" class="form-control" placeholder="Username" required >
            <label for="inputUsername" class=""></label>
        </div>
        <div class="form-label-group">
            <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
            <label for="inputPassword" class=""></label>
        </div><br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
         <div class="mt-4 mb-2 text-muted"><!--© 2020 Copyright:
            <a href=""> Polytechnic Institute of Leiria</a>-->
             <a href="<?= URL::toRoute('login/')?>">Back to Login</a>
        </div>
    </form>
</div>
</body>


