<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

$users = Data::get('users');

if(isset($_SESSION['loggedIn'])){
    Layout::includeLayout('headerLoggedIn');
}else{
    Layout::includeLayout('headerNotLoggedIn');
}


?>


<h1 style="text-align: center; margin-top: 100px">Backoffice</h1>



<div style="margin-top: 3%" class="container">

    <form action="<?=URL::toRoute('admin/searchUser')?>" method="post">
    <input type="text" id="inputUsername" placeholder="Username" name="username">
    <button>Pesquisar</button>
    </form>


    <?php
    if(isset($_SESSION['notFound'])){
        echo '<br><p style="color:red; font-size: 18px">'.$_SESSION['notFound'].'</p>';
        $_SESSION['notFound'] = null;
    } ?>



    <br>

    <table class="table table-hover">
        <thead>
        <tr>
            <th>Username</th>
            <th>Bloqueada</th>
            <th>Data</th>
            <th></th>
        </tr>
        </thead>
        <tbody>

        <?php
        if(!(isset($_SESSION['userSearched']))){ ?>
            <?php foreach ($users as $user) {
                if($user->admin == 0){ ?>
                    <th><?=$user->username?></th>
                    <?php if($user->bloqueado != 0){?>
                        <th style="padding-left: 45px">X</th>
                    <?php }else{ ?>
                        <th></th>
                    <?php }?>
                    <th><?=$user->databloqueado?></th>
                    <?php if($user->bloqueado == 0) {
                        echo '<form action="'. URL::toRoute('admin/blockUser', $user->id) .'"><th><button>Bloquear</button></th></form>';
                    }else{
                        echo '<form action="'. URL::toRoute('admin/unblockUser', $user->id) .'"><th><button>Desbloquear</button></th></form>';
                    } ?>
                    </tr>
                <?php }
            } ?>
        <?php }else{ ?>


                    <th><?=$_SESSION['userSearched']->username?></th>
                    <?php if($_SESSION['userSearched']->bloqueado != 0){?>
                        <th style="padding-left: 45px">X</th>
                    <?php }else{ ?>
                        <th></th>
                    <?php }?>
                    <th><?=$_SESSION['userSearched']->dataBloqueado?></th>
                    <?php if($_SESSION['userSearched']->bloqueado == 0) {
                        echo '<form action="'. URL::toRoute('admin/blockUser', $_SESSION['userSearched']->id) .'"><th><button>Bloquear</button></th></form>';
                    }else{
                        echo '<form action="'. URL::toRoute('admin/unblockUser', $_SESSION['userSearched']->id) .'"><th><button>Desbloquear</button></th></form>';
                    } ?>
                    </tr>

          <?php
            $_SESSION['userSearched'] = null;
        } ?>

        </tbody>
    </table>
</div>

</body>
</html>