<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;



//Verifica se o utilizador tem login feito
if(Session::has('userData')){
    Layout::includeLayout('headerLoggedIn');
}else{
    Layout::includeLayout('headerNotLoggedIn');
}

$users = Data::get('users');
$usersFound = Data::get('usersFound');
?>


<h1 style="margin-top: 7%" class="text-center">Backoffice</h1>



<div class="container mt-5">

    <div class="search-container mb-4">
        <div class="form-inline">
            <form action="<?=URL::toRoute('admin/searchUser')?>" method="post">
                <input type="text" id="inputUsername" class="form-control" style="width: 250px" placeholder="Pesquise por um utilizador" name="username">
                <button class="btn btn-info"><i class="fa fa-search"></i></button>
            </form>
            <form action="<?=URL::toRoute('admin/clearSearch')?>" method="post">
                <button class="btn btn-primary ml-1">Limpar</button>
            </form>
        </div>
    </div>

    <?php
    if(Session::has('notFound')){?>
        <div style="background-color: #e66767; border: 1px solid #3c3836; width: 35%; padding: 1%;" class=" mt-5 rounded text-center">
            <h5 style="color: whitesmoke; font-size: 22px"><?php echo Session::get('notFound') ?> <i class="fa fa-exclamation-circle"></i></h5>
        </div>
        <?php
        Session::remove('notFound');
    } ?>

    <br>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Nome de utilizador</th>
            <th>Bloqueada</th>
            <th>Data</th>
            <th></th>
        </tr>
        </thead>
        <tbody>

        <?php
        //Verifica se houve alguma pesquisa
        if(!Session::has('userSearched') || Session::get('userSearched') == null){?>
            <?php foreach ($users as $user) {
                if($user->admin == 0){ ?>
                    <tr>
                    <td><?=$user->username?></td>
                    <?php if($user->bloqueado != 0){?>
                        <td style="padding-left: 45px"> <i style="color: red" class="fa fa-ban"></i></td>
                    <?php }else{ ?>
                        <td></td>
                    <?php }?>
                    <td><?=$user->databloqueado?></td>
                    <?php if($user->bloqueado == 0) {
                        echo '<form action="'. URL::toRoute('admin/blockUser', $user->id) .'"><td><button class="btn btn-default"><i style="color: red; font-size: 20px;" class="fa fa-times-circle"></i></button></td></form>';
                    }else{
                        echo '<form action="'. URL::toRoute('admin/unblockUser', $user->id) .'"><td><button class="btn btn-default"><i style="color: green; font-size: 20px;" class="fa fa-check-circle"></i></button></td></form>';
                    } ?>
                    </tr>
                <?php }
            } ?>
        <?php }else{ ?>
                <?php if($usersFound->admin == 0){?>
                <tr>
                    <td><?=$usersFound->username?></td>
                    <?php if($usersFound->bloqueado != 0){?>
                        <td style="padding-left: 45px"><i style="color: red" class="fa fa-ban"></i></td>
                    <?php }else{ ?>
                        <td></td>
                    <?php }?>
                    <td><?=$usersFound->databloqueado?></td>
                    <?php if($usersFound->bloqueado == 0) {
                        echo '<form action="'. URL::toRoute('admin/blockUser', $usersFound->id) .'"><td><button class="btn btn-default"><i style="color: red" class="fa fa-times-circle"></i></button></td></form>';
                    }else{
                        echo '<form action="'. URL::toRoute('admin/unblockUser', $usersFound->id) .'"><td><button class="btn btn-default"><i style="color: green" class="fa fa-check-circle"></i></button></td></form>';
                    } ?>
                </tr>
        <?php }
            //Session::set('userSearched', null);
            Session::remove('userSearched');
                Tracy\Debugger::barDump($_SESSION,'teste');
        } ?>

        </tbody>
    </table>
</div>

<?php Layout::includeLayout('footerproject'); ?>