<?php

use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;

//Verifica se o utilizador tem login feito
if(Session::has('userData')){
    Layout::includeLayout('headerLoggedIn');
}else{
    Layout::includeLayout('headerNotLoggedIn');
}

?>
<body>
<div style="background-color: #a31515; border: 1px solid #3c3836; width: 45%;" class="container mt-5 rounded">
   <div class="container mt-3 text-center">
       <i style="color: white; font-size: 55px;" class="fa fa-ban"></i>
   </div>
    <div class="text-center">
        <?php
        if(Session::has('notLoggedIn')){
            echo '<br><p style="color:white; font-size: 18px">'.Session::get('notLoggedIn').'</p>';
            Session::remove('notLoggedIn');
        }

        if(Session::has('notAdmin')){
            echo '<br><p style="color:white; font-size: 18px">'.Session::get('notAdmin').'</p>';
            Session::remove('notAdmin');
        }
        ?>
    </div>
</div>
<?php Layout::includeLayout('footerproject');?>