<?php

use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;

//Verifica se o utilizador tem login feito
if(/*isset($_SESSION['loggedIn'])*/Session::has('userData')){
    Layout::includeLayout('headerLoggedIn');
}else{
    Layout::includeLayout('headerNotLoggedIn');
}
?>
<body>
<div style="background-color: #a31515; border: 1px solid #3c3836; width: 45%;" class="container mt-5 rounded">
   <div class="container mt-3 text-center">
       <i style="color: white; font-size: 55px;" class="fa fa-ban"></i>
   </div>
    <div class="text-center">
        <?php
        if(/*isset($_SESSION['notLoggedIn'])*/Session::has('notLoggedIn')){
            echo '<br><p style="color:white; font-size: 18px">'.Session::get('notLoggedIn').'</p>';
            Session::set('notLoggedIn',null);
        }

        if(/*isset($_SESSION['notAdmin'])*/Session::has('notAdmin')){
            echo '<br><p style="color:white; font-size: 18px">'.Session::get('notAdmin').'</p>';
            Session::set('notLoggedIn',null);
        }
        ?>
    </div>
</div>


</body>




<?php Layout::includeLayout('footerproject');?>