<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

//Verifica se o utilizador tem login feito
if(Session::has('userData')){
    Layout::includeLayout('headerLoggedIn');
}else{
    Layout::includeLayout('headerNotLoggedIn');
}

$valorDado = Data::get('valorDado');
//$numArray = Data::get('numArray');
$status = Data::get('status');
$statusGate = Data::get('statusGate');
$clickedGate = Data::get('clickedGate');

\Tracy\Debugger::barDump($clickedGate, "SESSION");
\Tracy\Debugger::barDump(Session::has('controlDiceRoll'),'teste');
?>
<h2 style="margin-top: 5%" class="text-center">Shut the Box</h2>
<div style="background-color: #e0e0ca; border: 1px solid #8A7B52; width: 55%;" class="container mt-4 rounded">
    <div class="gameBox">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4 text-center">
                <form method="post" action="<?=URL::toRoute('game/iniciarJogo')?>">
                    <button type="submit" class="btn btn-success text-center" style="margin: 5px;">PLAY</button>
                </form>
            </div>
            <div class="col-md-4"></div>
        </div>
        <div style="margin: 20px;" >
            <div class="btn-group">
                <form method="post" action="<?=URL::toRoute('game/bloquearNumero')?>">
                <?php for($i = 1; $i < 10; $i++){ ?>
                    <?php if(isset($_SESSION['numBloq']) && in_array($i, $_SESSION['numBloq'])) { ?>
                        <div class="btn-group">
                            <button type="submit" class="btn btn-lg btn-dark" disabled name="portoes" value="<?=$i?>" id="button<?=$i?>" style="margin-right: 20px; padding: 30px;"><?=$i?></button>
                        </div>
                    <?php } else if(/*!isset($_SESSION['controlDiceRoll'])*/!Session::has('controlDiceRoll')){ ?>
                    <div class="btn-group">
                        <button type="submit" class="btn btn-lg btn-dark" disabled name="portoes" style="background-color: #00D3B6; padding: 30px; margin: 15px;" value="<?=$i?>" id="button<?=$i?>" style="margin-right: 20px; padding: 30px;"><?=$i?></button>
                    </div>
                    <?php } else if(/*isset($_SESSION['controlDiceRoll'])*/Session::has('controlDiceRoll')){ ?>
                    <div class="btn-group">
                        <button type="submit" class="btn btn-lg btn-dark" enabled name="portoes" style="background-color: #00D3B6; padding: 30px; margin: 15px;" value="<?=$i?>" id="button<?=$i?>" style="margin-right: 20px; padding: 30px;"><?=$i?></button>
                    </div>
                    <?php } else { ?>
                        <div class="btn-group">
                            <button type="submit" class="btn btn-lg btn-dark" <?=$statusGate?> name="portoes" style="background-color: #00D3B6; padding: 30px; margin: 15px;" value="<?=$i?>" id="button<?=$i?>" style="margin-right: 20px; padding: 30px;"><?=$i?></button>
                        </div>
                    <?php } ?>
                <?php } ?>
                </form>
            </div>
        </div>
        <div style="background-color: #3c763d; border: 1px solid #8A7B52; height: 235px; margin: 20px;" class="rollDices">
            <div style="height: 80%;" class="col-xs-1 text-center">

                <?php if($valorDado != null){ ?>

                    <img class="img-fluid rounded mt-5" id="dado1" src="<?= Asset::image('dado'.$valorDado[0].'.png')?>" alt="" height="85" width="85">
                    <img class="img-fluid rounded mt-5" id="dado2" src="<?= Asset::image('dado'.$valorDado[1].'.png')?>" alt="" height="85" width="85">

                <?php } else { ?>

                    <img class="img-fluid rounded mt-5" id="dado1" src="<?= Asset::image('dado6.png')?>" alt="" height="85" width="85">
                    <img class="img-fluid rounded mt-5" id="dado2" src="<?= Asset::image('dado6.png')?>" alt="" height="85" width="85">

                <?php } ?>

            </div>
        </div>

        <form method="post" action="<?= URL::toRoute('game/mostrarDado')?>">
            <?php if(isset($_SESSION['controlDiceRoll'])) { ?>
                <div style="margin-right: 250px; margin-left: 250px;" class=" mt-2 ml-5 mr-5 mb-3">
                    <button class="btn btn-lg btn-danger btn-block" disabled <?=$status?>><?=Session::get('controlDiceRoll')?></button>
                </div>
            <?php } else { ?>
                <div style="margin-right: 250px; margin-left: 250px;" class=" mt-2 ml-5 mr-5 mb-3">
                    <button class="btn btn-lg btn-danger btn-block" <?=$status?>>Lançar Dados!</button>
                </div>
                <div class="text-center">
                    <?php
                    if(/*isset($_SESSION['finalJogo'])*/Session::has('finalJogo')){
                        echo '<br><p style="color:green; font-size: 22px">'./*$_SESSION['finalJogo']*/Session::get('finalJogo').'</p>';
                        //$_SESSION['finalJogo'] = null;
                        //Session::set('finalJogo',null);
                        Session::remove('finalJogo');
                    }
                    ?>
                </div>
            <?php } ?>
        </form>

    </div>
</div>

<?php Layout::includeLayout('footerproject'); ?>