<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;




if(isset($_SESSION['loggedIn'])){
    Layout::includeLayout('headerLoggedIn');
}else{
    Layout::includeLayout('headerNotLoggedIn');
}


?>


<div style="padding-top: 56px" class="container">

<!-- Heading Row -->
<div class="row align-items-center my-5">
    <div class="col-lg-7">
        <img class="img-fluid rounded mb-4 mb-lg-0"> <!--src="http://placehold.it/900x400" alt=""-->
    </div>
    <!-- /.col-lg-8 -->
    <div class="col-lg-5">
        <h1 class="font-weight-light">Bem-vindo ao Shut the Box Game</h1>
        <p>Shut The Box é um jogo de dados, fácil de jogar e de aprender</p>
        <a href="<?=URL::toRoute('stbox/game')?>" class="btn btn-primary custum-btn" href="#">Clica para jogar</a>
    </div>
    <!-- /.col-md-4 -->
</div>
    <br>
<!-- /.row -->


<!-- Content Row -->
<div class="row">
    <div class="col-md-4 mb-5">
        <div class="card h-100">
            <div class="card-body">
                <h2 class="card-title">Regras</h2>
                <p class="card-text">Veja as regras do jogo, na nossa página de regras.</p>
            </div>
            <div class="card-footer">
                <a href="<?= URL::toRoute('stbox/rules')?>" class="btn btn-primary btn-sm">Veja as regras</a>
            </div>
        </div>
    </div>
    <!-- /.col-md-4 -->
    <?php if(!(isset($_SESSION['loggedIn']))){?>
    <div class="col-md-4 mb-5">
        <div class="card h-100">
            <div class="card-body">
                <h2 class="card-title">Faça o login aqui!</h2>
                <p class="card-text">Para usufruir das várias funcionalidades do site, faça login.</p>
            </div>
            <div class="card-footer">
                <a href="<?= URL::toRoute('stbox/login')?>" class="btn btn-primary btn-sm">Autentica-te aqui</a>
            </div>
        </div>
    </div>
    <?php }?>

    <?php if(isset($_SESSION['loggedIn'])){?>
    <div class="col-md-4 mb-5">
        <div class="card h-100">
            <div class="card-body">
                <h2 class="card-title">Top 10</h2>
                <p class="card-text">Veja na página de Top 10 quais são os melhores jogadores.</p>
            </div>
            <div class="card-footer">
                <a href="<?= URL::toRoute('stbox/top10')?>" class="btn btn-primary btn-sm">Veja o Top 10</a>
            </div>
        </div>
    </div>
    <?php }?>

    <!-- /.col-md-4 -->
    <?php if(!(isset($_SESSION['loggedIn']))){?>
    <div class="col-md-4 mb-5">
        <div class="card h-100">
            <div class="card-body">
                <h2 class="card-title">Não estás registado?</h2>
                <p class="card-text">Para conseguires jogar, tens de estar registado no site.</p>
            </div>
            <div class="card-footer">
                <a href="<?= URL::toRoute('stbox/register')?>" class="btn btn-primary btn-sm">Regista-te aqui</a>
            </div>
        </div>
    </div>
    <?php }?>
    <!-- /.col-md-4 -->

    <?php if(isset($_SESSION['loggedIn'])){?>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">Histórico de Partidas</h2>
                    <p class="card-text">Consulta aqui as suas mais recentes partidas.</p>
                </div>
                <div class="card-footer">
                    <a href="<?= URL::toRoute('stbox/matches')?>" class="btn btn-primary btn-sm">Veja o histórico</a>
                </div>
            </div>
        </div>
    <?php }?>

</div>
<!-- /.row -->

</div>
<!-- /.container -->

</body>

<?php Layout::includeLayout('footerproject'); ?>
