<?php

use ArmoredCore\MagicBlankModel;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Layout;


//Verifica se o utilizador tem login feito
if(Session::has('userData')){
    Layout::includeLayout('headerLoggedIn');
}else{
    Layout::includeLayout('headerNotLoggedIn');
}

$user = Data::get('userError');
?>


    <body class="text-center">
    <div class="container" style="margin-top: 100px">
    <form class="form-signin" method="post" action="<?=Url::toRoute('user/login')?>">
        <img class="mb-4" src="<?= Asset::image('dices.png')?>" alt="" width=92" height="92">
        <h1 class="h3 mb-4 font-weight-normal">Shut the Box Game</h1>

            <label for="inputUsername" class=""</label>
            <input type="text" id="inputUsername"  class="form-control" placeholder="Nome de utilizador" required autofocus name="username" value="<?php if(!$user instanceof MagicBlankModel)echo $user?>">

            <label for="inputPassword" class=""></label>
            <input type="password" id="inputPassword" class="form-control" placeholder="Palavra-passe" required name="password">

<?php

if(Session::has('loginErrors')){
    echo '<br><p style="color:red; font-size: 18px">'.Session::get('loginErrors').'</p>';
    Session::destroy();
}

if(Session::has('bloqueado')){
    echo '<br><p style="color:red; font-size: 18px">'.Session::get('bloqueado').'</p>';
    Session::destroy();
}

if(Session::has('notLoggedIn')){
    echo '<br><p style="color:red; font-size: 18px">'.Session::get('notLoggedIn').'</p>';
    Session::destroy();
}

if(Session::has('blankField')){
    echo '<br><p style="color:red; font-size: 18px">'.Session::get('blankField').'</p>';
    Session::destroy();
}

if(Session::has('signInComplete')){
    echo '<br><p style="color:green; font-size: 18px">'.Session::get('signInComplete').'</p>';
    Session::destroy();
}
?>

        <button class="btn btn-lg btn-primary btn-block mt-4" type="submit">Iniciar Sessão</button>
        <div class="mb-3">
        </div>
    </form>
        <label>
            Não estás registado? Clica <a href="<?= URL::toRoute('stbox/register/')?>">AQUI</a> para te registares!
        </label>

    </div>
    </body>
<?php
Layout::includeLayout('footerproject');