<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Layout;


//Verifica se o utilizador tem login feito
/*if(isset($_SESSION['loggedIn'])){
    Layout::includeLayout('headerLoggedIn');
}else{
    Layout::includeLayout('headerNotLoggedIn');
}*/

if(Session::has('user')){
    Layout::includeLayout('headerLoggedIn');
} else {
    Layout::includeLayout('headerNotLoggedIn');
}

$user = Data::get('user');
ErrMgr::attach($user);
?>


    <body class="text-center">
    <div class="container" style="margin-top: 100px">
    <form class="form-signin" method="post" action="<?=Url::toRoute('user/login')?>">
        <img class="mb-4" src="<?= Asset::image('dices.png')?>" alt="" width=92" height="92">
        <h1 class="h3 mb-4 font-weight-normal">Shut the Box Game</h1>

        <label for="inputUsername" class=""</label>
        <input type="text" id="inputUsername"  class="form-control" placeholder="Nome de utilizador" autofocus name="username" value="<?= $user->username ?>">
        <?=  ErrMgr::bind('username') ?>

        <label for="inputPassword" class=""></label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Palavra-passe" name="password">
        <?=  ErrMgr::bind('password') ?>

<?php

if(isset($_SESSION['loginErrors'])){
    echo '<br><p style="color:red; font-size: 18px">'.$_SESSION['loginErrors'].'</p>';
    $_SESSION['loginErrors'] = null;
}

if(isset($_SESSION['bloqueado'])){
    echo '<br><p style="color:red; font-size: 18px">'.$_SESSION['bloqueado'].'</p>';
    $_SESSION['bloqueado'] = null;
    session_destroy();
}

if(isset($_SESSION['notLoggedIn'])){
    echo '<br><p style="color:red; font-size: 18px">'.$_SESSION['notLoggedIn'].'</p>';
    $_SESSION['notLoggedIn'] = null;
}
?>



        <button class="btn btn-lg btn-primary btn-block mt-4" type="submit">Iniciar Sessão</button>
        <div class="mb-3">
        </div>
    </form>
        <label>
            Não estás registado? Clica <a href="<?= URL::toRoute('stbox/register/')?>">AQUI</a> para te registares!
            <!--<a href="<?= URL::toRoute('stbox/register/')?>">Não estás registado? Clica aqui para te registares!</a>-->
        </label>

    </div>
    </body>
<?php
Layout::includeLayout('footerproject');