<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;

if(isset($_SESSION['loggedIn'])){
    Layout::includeLayout('headerLoggedIn');
}else{
    Layout::includeLayout('headerNotLoggedIn');
}

$matches = Data::get('matches');

?>


<h1 style="margin-top: 7%" class="text-center">Histórico de Partidas</h1>



<div class="container mt-5">

    <table class="table table-hover">
        <thead>
        <tr>
            <th>#</th>
            <th>Pontuação</th>
            <th>Resultado</th>
            <th>Data</th>
        </tr>
        </thead>
        <tbody>

        <tr>
    <?php
    $i = 1;

    if(!(isset($_SESSION['matches']))){ ?>
        <?php foreach ($matches as $match) {
             ?>
                <th><?= $i ?></th>
                <td><?=$match->pontuacao?></td>
                <?php  switch($match->vencedor){
                case 'G':
                    echo '<td>Ganho</td>';
                    break;
                case 'P':
                    echo '<td>Perdeu</td>';
                    break;
                case 'E':
                    echo '<td>Empatou</td>';
                    break; } ?>
                <td><?=$match->data?></td>
            </tr>
            <?php $i++; }?>

    <?php }?>
        </tbody>
    </table>
</div>


<?php Layout::includeLayout('footerproject'); ?>