<?php

use ArmoredCore\WebObjects\Layout;

Layout::includeLayout('headerLoggedIn');
?>


<h1 style="text-align: center; margin-top: 100px">Histórico de Partidas</h1>



<div style="margin-top: 3%" class="container">

    <table class="table table-hover">
        <thead>
        <tr>
            <th>#</th>
            <th>Pontuação</th>
            <th>Resultado</th>
            <th>Data</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th>3</th>
            <td>10</td>
            <td>Ganhou</td>
            <td>07/05/2020</td>
        </tr>
        <tr>
            <th>2</th>
            <td>14</td>
            <td>Perdeu</td>
            <td>05/05/2020</td>
        </tr>
        <tr>
            <th>1</th>
            <td>3</td>
            <td>Ganhou</td>
            <td>03/05/2020</td>
        </tr>
        </tbody>
    </table>
</div>

</body>
</html>