<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

//Verifica se o utilizador tem login feito
if(/*isset($_SESSION['loggedIn'])*/Session::has('userData')){
    Layout::includeLayout('headerLoggedIn');
}else{
    Layout::includeLayout('headerNotLoggedIn');
}

$user = Data::get('user');
?>


<body class="text-center">
<div style="max-width: 550px; border: 1px solid grey; padding-top: 2%; background-color: whitesmoke; margin-top: 50px" class="container">
    <form class="form-signin" method="post" action="<?=URL::toRoute('user/update', $user->id)?>">
        <!--        <img class="mb-4" src="" alt="" width=92" height="92">-->
        <h1 style="padding-bottom: 2%;" class="h2 mb-3 font-weight-normal">Perfil - Informações Pessoais</h1>
        <div class="form-label-group">
            <input type="text" id="inputPrimeiroNome" class="form-control" placeholder="Nome próprio" required autofocus name="primeiro_nome" value="<?=$user->primeiro_nome?>">
            <br>
        </div >
        <div class="form-label-group">
            <input type="text" id="inputApelido" class="form-control" placeholder="Apelido" required autofocus name="apelido" value="<?=$user->apelido?>">
            <br>
        </div >
        <div class="form-label-group">
            <input type="date" id="inputDataNascimento" class="form-control" placeholder="Data de Nascimento" required autofocus name="dataNascimento" value="<?=$user->datanascimento?>">
            <br>
        </div >
        <div class="form-label-group">
            <input type="email" id="inputEmail" class="form-control" placeholder="Email" required name="email" value="<?=$user->email?>">
            <br>
        </div><br>
        <h5 style="text-align: left">Alterar a palavra-passe:</h5>
        <div class="form-label-group">
            <input type="password" id="inputPassword" class="form-control" placeholder="Palavra-passe atual"  value="" name="password">
            <br>
        </div>
        <div class="form-label-group">
        <input type="password" id="newPassword" class="form-control" placeholder="Nova Palavra-passe"  value="" name="newPassword">
        <br>
</div><br>
        <?php
        if(/*isset($_SESSION['errorProfile'])*/Session::has('errorProfile')){
            echo '<p style="color:red; font-size: 18px">'.Session::get('errorProfile').'</p>';
            Session::set('errorProfile',null);
            //$_SESSION['errorProfile'] = null;
        }
        if(/*isset($_SESSION['updated'])*/Session::has('updated')){
            echo '<p style="color:green; font-size: 22px">'.Session::get('updated').'</p>';
            Session::set('updated',null);
            //$_SESSION['updated'] = null;
        }
        if(/*isset($_SESSION['clearCamp'])*/Session::has('clearCamp')){
            echo '<p style="color:red; font-size: 22px">'.Session::get('clearCamp').'</p>';
            Session::set('clearCamp',null);
            //$_SESSION['clearCamp'] = null;
        }
        ?>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Guardar Alterações</button>
        <br>
    </form>
</div>
</body>
<?php Layout::includeLayout('footerproject');

