<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

//Verifica se o utilizador tem login feito
if(Session::has('userData')){
    Layout::includeLayout('headerLoggedIn');
}else{
    Layout::includeLayout('headerNotLoggedIn');
}

$user = Data::get('userInfo');
ErrMgr::attach($user);
$userData = Session::get('userData');
$erro = Data::get('profileError');
?>


<body class="text-center">
<div style="max-width: 550px; border: 1px solid grey; padding-top: 2%; background-color: whitesmoke; margin-top: 50px" class="container">
    <form class="form-signin" method="post" action="<?=URL::toRoute('user/update', $user->id)?>">
        <h1 style="padding-bottom: 2%;" class="h2 mb-3 font-weight-normal">Perfil - Informações Pessoais</h1>
        <div class="form-label-group">
            <input type="text" id="inputPrimeiroNome" class="form-control" placeholder="Nome próprio" required autofocus name="primeiro_nome" value="<?=$user->primeiro_nome?>">
            <?= ErrMgr::bind('primeiro_nome') ?>
            <br>
        </div >
        <div class="form-label-group">
            <input type="text" id="inputApelido" class="form-control" placeholder="Apelido" required autofocus name="apelido" value="<?=$user->apelido?>">
            <?= ErrMgr::bind('apelido') ?>
            <br>
        </div >
        <div class="form-label-group">
            <input type="date" id="inputDataNascimento" class="form-control" placeholder="Data de Nascimento" required autofocus name="dataNascimento" value="<?=$userData->datanascimento?>">
            <br>
        </div >
        <div class="form-label-group">
            <input type="email" id="inputEmail" class="form-control" placeholder="Email" required name="email" value="<?=$user->email?>">
            <?= ErrMgr::bind('email') ?>
            <br>
        </div><br>
        <h5 style="text-align: left">Alterar a palavra-passe:</h5>
        <div class="form-label-group">
            <input type="password" id="inputPassword" class="form-control" placeholder="Palavra-passe atual"  value="" name="password">
            <br>
        </div>
        <div class="form-label-group">
        <input type="password" id="newPassword" class="form-control" placeholder="Nova Palavra-passe"  value="" name="newPassword">
</div><br>
        <?php
        if(Session::has('updated')){ ?>
            <div style="background-color: #7ce075; border: 1px solid #3c3836; width: 80%; padding: 3%; margin-bottom: 20px" class="container mt-1 rounded text-center">
                <h5 style="color: whitesmoke; font-size: 22px"><?php echo Session::get('updated') ?> <i class="fa fa-check"></i></h5>
            </div>
            <?php Session::remove('updated');
        }
        if(Session::has('error')){ ?>
            <div style="background-color: #e66767; border: 1px solid #3c3836; width: 80%; padding: 3%; margin-bottom: 20px" class="container mt-1 rounded text-center">
                <h5 style="color: whitesmoke; font-size: 22px"><?php echo Session::get('error') ?> <i class="fa fa-exclamation-circle"></i></h5>
            </div>
            <?php Session::remove('error');
        }
        ?>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Guardar Alterações</button>
        <br>
    </form>
</div>
<?php Layout::includeLayout('footerproject');

