<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Layout;

//Verifica se o utilizador tem login feito
if(isset($_SESSION['loggedIn'])){
    Layout::includeLayout('headerLoggedIn');
}else{
    Layout::includeLayout('headerNotLoggedIn');
}?>

<?php $user = Data::get('user');
?>


<div style="max-width: 550px; border: 1px solid grey; padding-top: 2%; background-color: whitesmoke; margin-top: 50px" class="container text-center">
    <form class="form-signin" method="post" action="<?=Url::toRoute('user/store') ?>">
<!--        <img class="mb-4" src="" alt="" width=92" height="92">-->
        <h1 style="padding-bottom: 2%;" class="h2 mb-3 font-weight-normal">REGISTE-SE AQUI</h1>
        <div class="form-label-group">
            <input type="text" id="inputPrimeiroNome" class="form-control" placeholder="Nome próprio" required autofocus name="primeiro_nome" value="<?=$user->primeiro_nome?>">
            <br>
        </div >
        <div class="form-label-group">
            <input type="text" id="inputApelido" class="form-control" placeholder="Apelido" required autofocus name="apelido" value="<?=$user->apelido?>">
            <br>
        </div >
        <div class="form-label-group">
            <input type="date" id="inputDataNascimento" class="form-control" placeholder="Data de Nascimento" required autofocus name="dataNascimento" value="<?=$user->datanascimento?>">
            <br>
        </div >
        <div class="form-label-group">
            <input type="email" id="inputEmail" class="form-control" placeholder="Email" required name="email" value="<?=$user->email?>">
            <br>
        </div>
        <div class="form-label-group">
            <input type="text" id="inputUsername" class="form-control" placeholder="Nome de utilizador" required name="username" value="<?=$user->username?>">
            <br>
        </div>
        <div class="form-label-group">
            <input type="password" id="inputPassword" class="form-control" placeholder="Palavra-passe" name="password" value="<?=$user->password?>">
            <br>
        </div><br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Registar</button>
    </form>
    <div class="mt-4 mb-2 text-muted">
        Se já criou conta faça login <a href="<?= URL::toRoute('stbox/login/')?>">AQUI</a>!
    </div>
</div>
</body>

<?php
Layout::includeLayout('footerproject');


