<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Layout;

//Verifica se o utilizador tem login feito
if(/*isset($_SESSION['loggedIn'])*/Session::has('userData')){
    Layout::includeLayout('headerLoggedIn');
}else{
    Layout::includeLayout('headerNotLoggedIn');
}

$user = Data::get('user');
?>


<body class="text-center">
<div style="max-width: 550px; border: 1px solid grey; padding-top: 2%; background-color: whitesmoke; margin-top: 50px" class="container">
    <form class="form-signin" method="post" action="<?=Url::toRoute('user/store') ?>">
<!--        <img class="mb-4" src="" alt="" width=92" height="92">-->
        <h1 style="padding-bottom: 2%;" class="h2 mb-3 font-weight-normal">REGISTE-SE AQUI</h1>
        <div class="form-label-group">
            <input type="text" id="inputPrimeiroNome" class="form-control" placeholder="Nome próprio" autofocus name="primeiro_nome">
            <br>
        </div >
        <div class="form-label-group">
            <input type="text" id="inputApelido" class="form-control" placeholder="Apelido" name="apelido">
            <br>
        </div >
        <div class="form-label-group">
            <input type="date" id="inputDataNascimento" class="form-control" placeholder="Data de Nascimento" name="dataNascimento">
            <br>
        </div >
        <div class="form-label-group">
            <input type="email" id="inputEmail" class="form-control" placeholder="Email" name="email">
            <br>
        </div>
        <div class="form-label-group">
            <input type="text" id="inputUsername" class="form-control" placeholder="Nome de utilizador" name="username">
            <br>
        </div>
        <div class="form-label-group">
            <input type="password" id="inputPassword" class="form-control" placeholder="Palavra-passe" name="password">
            <br>
        </div>
        <?php
        if(/*isset($_SESSION['signInError'])*/Session::has('signInError')){
            echo '<br><p style="color:red; text-align: center; font-size: 18px">'.Session::get('signInError').'</p>';
            Session::destroy();
        }
        ?>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Registar</button>
    </form>
    <div class="mt-4 mb-2 text-muted">
        Se já criou conta faça login <a href="<?= URL::toRoute('stbox/login/')?>">AQUI</a>!
    </div>
</div>
</body>

<?php
Layout::includeLayout('footerproject');


