<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

//Verifica se o utilizador tem login feito
if(isset($_SESSION['loggedIn'])){
    Layout::includeLayout('headerLoggedIn');
}else{
    Layout::includeLayout('headerNotLoggedIn');
}
?>


<h1 class="mt-5" style="text-align: center">Regras</h1>

<div style="max-width: 960px; margin: auto;margin-top: 100px">
    <p>O jogo começa com o jogador a lançar os dados e a fazer a soma dos dois dados.<br>
    Depois deve escolher uma combinação que faça exatamente o resultado dado pela soma dos dados, até que já não haja mais números virados para cima.</p>

    <p>Por exemplo, se o jogador lançar os dados e calhar 6 num e 3 no outro, a soma dos dois dados dá um total de 9.<br>
    O jogador depois deve escolher a combinação de peças que quer virar:</p>
        <ul>
            <li>9</li>
            <li>8 e 1</li>
            <li>7 e 2</li>
            <li>6 e 3</li>
            <li>5 e 4</li>
            <li>6,2 e 1</li>
            <li>5,3 e 1</li>
            <li>4,3 e 2</li>
        </ul>

    <p>Depois de escolher as peças o jogador repete o mesmo processo, até lançar os dados e a soma deles der um total, que não tenha nenhuma combinação ou até ter virado todos os números.<br>
    <br>As peças que ficarem por virar, são somadas e o resultado é os pontos do jogador. Ganha o jogador que obtiver menos pontos.</p>
</div>


<?php Layout::includeLayout('footerproject'); ?>