<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

//Verifica se o utilizador tem login feito
if(Session::has('userData')){
    Layout::includeLayout('headerLoggedIn');
}else{
    Layout::includeLayout('headerNotLoggedIn');
}

$top10 = Data::get('top10');
$erro = Data::get('top10erro');
?>

    <body>
    <div style="margin-top: 5%" class="container">
        <h1 class="text-center mb-5">Top 10</h1>

        <?php
        //Verifica se existe alguma partida no site
        if($top10 != null){?>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Nome de utilizador</th>
                    <th>Data</th>
                    <th>Pontos</th>
                </tr>
                </thead>
                <tbody>

                <?php
                $i = 1;
                foreach ($top10 as $top){?>
                    <tr>
                        <th><?=$i?></th>
                        <?php
                        //Faz-se um find para ir buscar o username através do id do user
                        $username = (User::find($top->user_id)->username)?>
                        <td><?= $username?></td>
                        <?php $data = $top->data->format('d-m-Y H:i:s');?>
                        <td><?=$data?></td>
                        <td><?=$top->pontuacao?></td>
                    </tr>
                    <?php
                    $i++;
                }?>
                </tbody>
            </table>
            <?php }else{ ?>
            //Senão devolve uma mensagem de aviso
            <div style="background-color: #668bb0; border: 1px solid #3c3836; width: 40%; padding: 3%;" class="container mt-5 rounded text-center">
                <h5 style="color: whitesmoke; font-size: 22px"><?php echo $erro ?> <i class="fa fa-exclamation-circle"></i></h5>
                <p style="font-size: 22px">Clica <a style="color: white" href="<?= URL::toRoute('game/iniciarJogo')?>">aqui</a> para jogar!</p>
            </div>
            <?php
        } ?>
    </div>

<?php Layout::includeLayout('footerproject');