<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;

//Verifica se o utilizador tem login feito
if(Session::has('userData')){
    Layout::includeLayout('headerLoggedIn');
}else{
    Layout::includeLayout('headerNotLoggedIn');
}

$top10 = Data::get('top10');

?>

    <body>
    <div style="margin-top: 5%" class="container">
        <h3>Top 10</h3>

        <?php
        if(Session::has('noTop')){
            echo '<br><p style="color:red; text-align: center; font-size: 22px">'.Session::get('noTop').'</p>';
            Session::remove('noTop');
        }
        ?>

        <table class="table table-hover">
            <thead>
            <tr>
                <th>#</th>
                <th>Nome de utilizador</th>
                <th>Data</th>
                <th>Pontos</th>
            </tr>
            </thead>
            <tbody>

            <?php
                $i = 1;
                foreach ($top10 as $top){ ?>
                    <tr>
                        <th><?=$i?></th>
                        <th><?=$top->users->username?></th>
                        <?php $data = $top->data->format('d-m-Y H:i:s');?>
                        <th><?=$data?></th>
                        <th><?=$top->pontuacao?></th>
                    </tr>
                    <?php
                    $i++;
            }?>
            </tbody>
        </table>

    </div>
<?php Layout::includeLayout('footerproject');