<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;

//Verifica se o utilizador tem login feito
if(isset($_SESSION['loggedIn'])){
    Layout::includeLayout('headerLoggedIn');
}else{
    Layout::includeLayout('headerNotLoggedIn');
}

$top10 = Data::get('top10');

?>

    <body>
    <div style="margin-top: 5%" class="container">
        <h3>Top 10</h3>

        <?php
        if(isset($_SESSION['noTop'])){
            echo '<br><p style="color:red; text-align: center; font-size: 18px">'.$_SESSION['noTop'].'</p>';
        }
        ?>

        <table class="table table-hover">
            <thead>
            <tr>
                <th>#</th>
                <th>Nome de utilizador</th>
                <th>Data</th>
                <th>Pontos</th>
            </tr>
            </thead>
            <tbody>

            <?php
            //Verifica se existe algum jogo no sistema, senão houver, devolve um aviso
            if(!(isset($_SESSION['noTop']))){
                $i = 1;
                foreach ($top10 as $top){ ?>
                    <tr>
                        <th><?=$i?></th>
                        <td><?=$top->username?></td>
                        <?php $data = date_create($top->data);
                        //Formata a data?>
                        <td><?=date_format($data,"d/m/Y")?></td>
                        <td><?=$top->pontuacao?></td>
                    </tr>
                    <?php
                    $i++;
                }
            }
            $_SESSION['noTop'] = null;?>

            </tbody>
        </table>

    </div>


    </body>

<?php Layout::includeLayout('footerproject');?>